name = "ProbNumODE"
uuid = "1e2eedd4-8c36-44ca-9a66-8045cdbbfc08"
authors = ["Nathanael Bosch"]
version = "0.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianDistributions = "43dcc890-d446-5863-8d1a-14597580bb8d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DiffEqBase = "6"
DiffEqDevTools = "2"
Distributions = "0.19, 0.20, 0.21, 0.22, 0.23, 0.24"
ForwardDiff = "0.10"
GaussianDistributions = "0.5"
Measurements = "2"
ModelingToolkit = "3"
Optim = "0.22, 1.0"
ProgressLogging = "0.1"
RecipesBase = "1"
Reexport = "0.2"
StaticArrays = "0.12"
StructArrays = "0.4"
TerminalLoggers = "0.1"
UnPack = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
