[deps]
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
MATLABDiffEq = "e2752cbe-bcf4-5895-8727-84ebc14a76bd"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciPyDiffEq = "505e40e9-d84e-434c-8501-7161967c02cb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
deSolveDiffEq = "0518478a-701b-4815-806c-24ad5cb92f09"
