[deps]
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MATLABDiffEq = "e2752cbe-bcf4-5895-8727-84ebc14a76bd"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProbNumDiffEq = "bf3e78b0-7d74-48a5-b855-9609533b56a5"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciPyDiffEq = "505e40e9-d84e-434c-8501-7161967c02cb"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
deSolveDiffEq = "0518478a-701b-4815-806c-24ad5cb92f09"

[compat]
DiffEqDevTools = "2.42.0"
deSolveDiffEq = "1.1.0"
